name: Hugo Website Build and Firebase Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Build Hugo
      uses: vedacomputing/build-hugo@v0.71.1
    - name: Deploy to Firebase
      uses: vedacomputing/deploy-firebase@v0.0.4
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: vedacomputing-3d1f5